CREATE TABLE USER (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT, 
	Name VARCHAR(50), 
	Email VARCHAR(30), 
	Password VARCHAR(30), 
	PRIMARY KEY (USER_ID)
); 

CREATE TABLE FAVOURITE_RECIPE (
	RECIPE_ID BIGINT NOT NULL, 
	USER_ID BIGINT NOT NULL, 
	TITLE VARCHAR(500), 
	INSTRUCTIONS VARCHAR(5000), 
	TIME_TO_WORK INT, 
	VEGAN TINYINT(1),
	VEGETARIAN TINYINT(1),
	ANTIALC TINYINT(1),
	PRIMARY KEY (RECIPE_ID, USER_ID)
);