CREATE TABLE FAVOURITE_RECIPE (
	ID BIGINT NOT NULL, 
	Recipe_ID BIGINT NOT NULL, 
	Title VARCHAR(500), 
	Instructions VARCHAR(5000), 
	Time_To_Work INT, 
	Vegan TINYINT(1),
	Vegetarian TINYINT(1),
	Antialc TINYINT(1),
	Img_Src VARCHAR(500), 
	User_ID BIGINT NOT NULL,
	PRIMARY KEY (Recipe_ID, User_ID)
);

CREATE TABLE USER (
	User_ID BIGINT NOT NULL AUTO_INCREMENT, 
	User_Name VARCHAR(30), 
	Password VARCHAR(30), 
	PRIMARY KEY (User_ID)
); 